### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by ujaveri** [johnzaro/RAMInfo13#1]
When I increase the font Size 
It doesn’t work. As you can see I had to turn on magnifier in screenshot 

![A9C02DA9-3813-42B4-A4D2-BDD157E4D011](https://user-images.githubusercontent.com/55907135/83347117-01b18d80-a33c-11ea-8136-937e1a73ec0f.jpeg)

**Comment by johnzaro** [comment]
Try and make width and height larger and tell me if that works

**Comment by ujaveri** [comment]
Thanks that worked. 
![EDDDC2F2-93EB-497F-B260-0A9D643D5A1E](https://user-images.githubusercontent.com/55907135/83352001-e8233c80-a361-11ea-922d-728d38c73471.png)
